server:
  port: ${SERVER_PORT:8080}

drawings:
  dir: ${DRAWINGS_DIR:C:/Users/it.production/OneDrive - MISUMI Group Inc/KVH_Fixed Asset - 2. Files/Request_PNG}
  # dir: ${DRAWINGS_DIR:C:/Users/KVH_IT_Mem_Viet/OneDrive - MISUMI Group Inc/Request_PNG}
  base-url: ${DRAWINGS_BASE_URL:} 

spring:
  application:
    name: fixed-asset-be

  datasource:
    url: jdbc:sqlserver://192.168.122.2:1433;databaseName=F2Database;encrypt=false;trustServerCertificate=true
    username: kproduct
    password: Tanphat@02032013
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 40
      minimum-idle: 10
      idle-timeout: 60000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

fixed-asset:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}

logging:
  level:
    root: INFO
    com.spc.fixedasset: INFO